version: "3.5"
services:
  node-dashboard.dnp.dappnode.eth:
    image: "node-dashboard.dnp.dappnode.eth:0.1.0"
    build:
      context: build
      args:
        UPSTREAM_VERSION: v0.0.1
    environment:
      NEXT_PUBLIC_BLOCKNATIVE_DAPP_ID: ""
      NEXT_PUBLIC_NODE_URL: "http://geth.dappnode:8545"
      NEXT_PUBLIC_XDAI_NODE_URL: "http://nethermind-xdai.dappnode:8545"
    restart: unless-stopped
